preset: recommended

risky: false

disabled:
  - align_double_arrow
  - unalign_equals
  - align_comments
  - align_phpdoc
  - phpdoc_align
  - phpdoc_annotation_without_dot
  - concat_without_spaces
